import styles from "./layout.module.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProductsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <nav className={styles.nav}>
        <a href="/">Female</a>
        <a href="/">Male</a>
      </nav>
      <section className={styles.product}>{children}</section>
    </>
  );
}
